// Hey Emacs, this is -*- coding: utf-8 -*-

import type { Metadata, NextPage } from 'next';
import { Inter } from 'next/font/google';

import '~/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  children: React.ReactNode;
}

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: NextPage<Props> = ({ children }) => {
  // <html lang="en">
  //   <body className={inter.className}>
  //     <main>{children}</main>
  //   </body>
  // </html>
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export { metadata };
export default RootLayout;
